FROM golang:1.22-alpine as build
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN go build -o server cmd/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=build /app/server .
EXPOSE 8080
CMD ["./server"]
